CREATE DATABASE IF NOT EXISTS home_study;
USE home_study;
CREATE TABLE IF NOT EXISTS aluno(
curso VARCHAR (100),
periodo VARCHAR (100)
);
CREATE TABLE IF NOT EXISTS usuario(
id  INT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR (100) NOT NULL,
email VARCHAR (100) NOT NULL UNIQUE,
telefone VARCHAR (100) NOT NULL UNIQUE,
senha VARCHAR (100) NOT NULL
);
CREATE TABLE IF NOT EXISTS imovel(
nome VARCHAR (100) NOT NULL,
endereço VARCHAR (100) NOT NULL,
informacao VARCHAR (100) NOT NULL,
valor VARCHAR (100) NOT NULL
);
